package gl;

import a80.l;
import au0.j;
import com.bandlab.bandlab.AppGraph$$;
import com.bandlab.media.player.impl.g0;
import com.facebook.internal.t0;
import dh0.i;
import iw1.b;
import lmjxuqdtp.jvm.internal.o;
import m71.q;
import mr.z3;
import wm.f0;

/* JADX INFO: compiled from: r8-map-id-9e936228ea1ea2cc679ed5186cc1349ef706487dc89ec4e25d4a3ea878769de6 */
/* JADX INFO: loaded from: classes.dex */
public final class e {
    public final c A;
    public final b B;
    public final c C;
    public final jw1.f D;
    public final jw1.f E;
    public final jw1.f F;
    public final jw1.f G;
    public final jw1.f H;
    public final c I;
    public final jw1.f J;
    public final c K;
    public final au0.g L;
    public final c M;
    public final c N;
    public final c O;
    public final d P;
    public final df0.a Q;
    public final i R;
    public final d S;
    public final d T;
    public final au0.g U;
    public final au0.g V;
    public final c W;
    public final c X;
    public final c Y;
    public final au0.g Z;
    public final AppGraph$$.MetroGraph a;
    public final jw1.f a0;
    public final jw1.c b;
    public final c b0;
    public final jw1.c c;
    public final c c0;
    public final jw1.c d;
    public final b d0;
    public final jw1.c e;
    public final b e0;

    /* JADX INFO: renamed from: f, reason: collision with root package name */
    public final jw1.c f183f;
    public final d f0;
    public final jw1.c g;
    public final d g0;
    public final c h;
    public final au0.g h0;
    public final b i;
    public final d i0;

    /* JADX INFO: renamed from: j, reason: collision with root package name */
    public final b f184j;
    public final d j0;
    public final c k;
    public final d k0;
    public final df0.a l;
    public final d l0;
    public final c m;
    public final a m0;
    public final df0.a n;
    public final b n0;
    public final b o;
    public final d o0;
    public final c p;
    public final d p0;
    public final c q;
    public final d q0;
    public final c r;
    public final au0.g r0;
    public final g s;
    public final d s0;
    public final c t;
    public final d t0;
    public final c u;
    public final a81.d u0;
    public final b v;
    public final b v0;
    public final c w;
    public final b x;
    public final c y;
    public final c z;

    public e(AppGraph$$.MetroGraph metroGraph) {
        this.a = metroGraph;
        new jw1.f(this);
        this.b = new jw1.c();
        this.c = new jw1.c();
        this.d = new jw1.c();
        this.e = new jw1.c();
        this.f183f = new jw1.c();
        this.g = new jw1.c();
        c cVar = new c(this, 1);
        this.h = cVar;
        b bVarF = jw1.b.f(new f(this, cVar, 1));
        this.i = bVarF;
        this.f184j = jw1.b.f(new g(this, bVarF, 1));
        c cVar2 = new c(this, 2);
        this.k = cVar2;
        this.l = new df0.a(this, cVar2, 26);
        c cVar3 = new c(this, 3);
        this.m = cVar3;
        df0.a aVar = new df0.a(this, cVar3, 27);
        this.n = aVar;
        b bVar = this.f184j;
        df0.a aVar2 = this.l;
        o.h(bVar, "acTransport");
        o.h(aVar2, "audioCoreWorkDirs");
        this.o = jw1.b.f(new j(this, bVar, aVar2, aVar, 8));
        this.p = new c(this, 4);
        this.q = new c(this, 5);
        this.r = new c(this, 6);
        this.s = new g(this, new c(this, 7), 0);
        this.t = new c(this, 8);
        c cVar4 = new c(this, 9);
        this.u = cVar4;
        this.v = jw1.b.f(new um.a(cVar4, 6));
        this.w = new c(this, 0);
        this.x = jw1.b.f(new a10.d(1, this));
        this.y = new c(this, 11);
        this.z = new c(this, 12);
        this.A = new c(this, 13);
        c cVar5 = this.m;
        o.h(cVar5, "fxManagerProvider");
        jw1.d dVar = new jw1.d(new z3(cVar5, 23));
        this.B = dVar;
        c cVar6 = new c(this, 14);
        this.C = cVar6;
        c cVar7 = this.A;
        o.h(cVar7, "membersEffectsRepo");
        this.D = new jw1.f(new ml.a(new jx0.h(dVar, cVar7, cVar6, 10)));
        b bVar2 = this.B;
        c cVar8 = this.A;
        c cVar9 = this.C;
        o.h(bVar2, "pedalAdapter");
        o.h(cVar8, "membersEffectsRepo");
        o.h(cVar9, "membershipRepo");
        this.E = new jw1.f(new nl.a(new q(bVar2, cVar8, cVar9)));
        c cVar10 = this.A;
        b bVar3 = this.B;
        c cVar11 = this.C;
        o.h(cVar10, "membersEffectsRepo");
        o.h(bVar3, "pedalAdapter");
        o.h(cVar11, "membershipRepo");
        this.F = new jw1.f(new ol.a(new q(cVar10, bVar3, cVar11)));
        b bVar4 = this.B;
        c cVar12 = this.A;
        c cVar13 = this.C;
        o.h(bVar4, "pedalAdapter");
        o.h(cVar12, "membersEffectsRepo");
        o.h(cVar13, "membershipRepo");
        this.G = new jw1.f(new ql.a(new q(bVar4, cVar12, cVar13)));
        c cVar14 = this.A;
        b bVar5 = this.B;
        c cVar15 = this.C;
        o.h(cVar14, "membersEffectsRepo");
        o.h(bVar5, "pedalAdapter");
        o.h(cVar15, "membershipRepo");
        this.H = new jw1.f(new rl.a(new q(cVar14, bVar5, cVar15)));
        b bVar6 = this.B;
        c cVar16 = this.A;
        c cVar17 = this.C;
        o.h(bVar6, "pedalAdapter");
        o.h(cVar16, "membersEffectsRepo");
        o.h(cVar17, "membershipRepo");
        jw1.f fVar = new jw1.f(new sl.a(new q(bVar6, cVar16, cVar17)));
        jw1.f fVar2 = this.D;
        jw1.f fVar3 = this.E;
        jw1.f fVar4 = this.G;
        jw1.f fVar5 = this.H;
        jw1.f fVar6 = this.F;
        o.h(fVar2, "cleanLimiterControllerFactory");
        o.h(fVar3, "multiBandControllerFactory");
        o.h(fVar4, "shimmerControllerFactory");
        o.h(fVar5, "standardFxControllerFactory");
        o.h(fVar6, "oneKnobControllerFactory");
        a80.d dVar2 = new a80.d();
        dVar2.b = fVar2;
        dVar2.c = fVar3;
        dVar2.a = fVar;
        dVar2.d = fVar4;
        dVar2.e = fVar5;
        dVar2.f = fVar6;
        jw1.f fVar7 = new jw1.f(new kl.a(dVar2));
        c cVar18 = new c(this, 15);
        this.I = cVar18;
        c cVar19 = new c(this, 16);
        c cVar20 = new c(this, 17);
        c cVar21 = new c(this, 18);
        c cVar22 = new c(this, 19);
        c cVar23 = new c(this, 10);
        c cVar24 = new c(this, 25);
        b bVar7 = this.x;
        c cVar25 = this.m;
        o.h(bVar7, "audioControllerScope");
        o.h(cVar25, "fxMetadataManagerProvider");
        this.J = new jw1.f(new jl.a(new dl.c(bVar7, cVar20, cVar19, cVar18, cVar21, cVar22, cVar24, cVar25, fVar7, cVar23, 3)));
        this.K = new c(this, 26);
        this.L = new au0.g(4, this);
        this.M = new c(this, 27);
        this.N = new c(this, 28);
        this.O = new c(this, 29);
        this.P = new d(this, 0);
        g gVar = this.s;
        o.h(gVar, "resourcesProvider");
        this.Q = new df0.a(gVar, 3);
        this.R = i.a;
        this.S = new d(this, 1);
        this.T = new d(this, 2);
        this.U = new au0.g(1, this);
        this.V = new au0.g(2, this);
        this.W = new c(this, 20);
        this.X = new c(this, 21);
        this.Y = new c(this, 22);
        this.Z = new au0.g(3, this);
        b bVar8 = this.x;
        c cVar26 = this.C;
        c cVar27 = this.z;
        o.h(bVar8, "scope");
        o.h(cVar26, "membershipRepo");
        o.h(cVar27, "remoteConfig");
        this.a0 = new jw1.f(new vl.i(new q(bVar8, cVar26, cVar27)));
        this.b0 = new c(this, 23);
        this.c0 = new c(this, 24);
        this.d0 = new jw1.d(new f(this, this.h, 0));
        c cVar28 = this.K;
        c cVar29 = this.b0;
        c cVar30 = this.c0;
        o.h(cVar28, "focuses");
        o.h(cVar29, "routes");
        o.h(cVar30, "clock");
        j jVar = new j(cVar28, cVar29, cVar30, 11);
        b bVar9 = this.x;
        b bVar10 = this.i;
        b bVar11 = this.d0;
        c cVar31 = this.O;
        o.h(cVar31, "pref");
        yt.a aVar3 = new yt.a(cVar31, 5);
        o.h(bVar9, "scope");
        o.h(bVar10, "outDevice");
        o.h(bVar11, "inDevice");
        this.e0 = new jw1.d(new a81.a(this, jVar, bVar9, bVar10, bVar11, aVar3));
        this.f0 = new d(this, 6);
        this.g0 = new d(this, 7);
        this.h0 = new au0.g(6, this);
        this.i0 = new d(this, 8);
        this.j0 = new d(this, 9);
        this.k0 = new d(this, 10);
        this.l0 = new d(this, 11);
        this.m0 = new a(this, 2);
        b bVar12 = this.e0;
        b bVar13 = this.x;
        b bVar14 = this.f184j;
        o.h(bVar14, "transport");
        v31.a aVar4 = new v31.a(bVar14, 9);
        a aVar5 = this.m0;
        o.h(bVar12, "io");
        o.h(bVar13, "scope");
        o.h(aVar5, "timerUpdateFrequencyMs");
        this.n0 = new jw1.d(new wl.f(bVar12, bVar13, aVar4, aVar5, 1));
        this.o0 = new d(this, 12);
        this.p0 = new d(this, 13);
        this.q0 = new d(this, 3);
        this.r0 = new au0.g(5, this);
        this.s0 = new d(this, 4);
        this.t0 = new d(this, 5);
        jw1.c cVar32 = this.g;
        this.u0 = new a81.d(cVar32, 12);
        b bVar15 = this.e0;
        b bVar16 = this.f184j;
        c cVar33 = this.O;
        b bVar17 = this.x;
        c cVar34 = this.X;
        au0.g gVar2 = this.Z;
        c cVar35 = this.z;
        o.h(bVar16, "transport");
        o.h(cVar33, "preferences");
        o.h(bVar17, "coroutineScope");
        o.h(cVar34, "mixEditorStorageController");
        o.h(gVar2, "positionPollDispatcher");
        o.h(cVar35, "remoteConfig");
        vl.a aVar6 = new vl.a(bVar16, cVar32, cVar33, bVar17, cVar34, gVar2, cVar35);
        d dVar3 = this.j0;
        c cVar36 = this.k;
        o.h(cVar36, "mixEditorStorage");
        a51.b bVar18 = new a51.b(cVar36, 16);
        c cVar37 = this.r;
        d dVar4 = this.k0;
        c cVar38 = this.k;
        c cVar39 = this.u;
        au0.g gVar3 = this.h0;
        o.h(cVar38, "storage");
        o.h(cVar39, "apiServiceFactory");
        o.h(gVar3, "codecs");
        j jVar2 = new j(cVar38, cVar39, gVar3, 4);
        b bVar19 = this.x;
        jw1.c cVar40 = this.g;
        c cVar41 = this.W;
        i iVar = this.R;
        d dVar5 = this.i0;
        g gVar4 = this.s;
        df0.a aVar7 = this.Q;
        o.h(cVar41, "meResManager");
        o.h(iVar, "trackColorsProvider");
        o.h(dVar5, "cachedSoundBanksApi");
        o.h(gVar4, "resourcesProvider");
        o.h(aVar7, "trackNameProvider");
        com.bandlab.audio.controller.audioToMidi.h hVar = new com.bandlab.audio.controller.audioToMidi.h(cVar40, cVar41, iVar, dVar5, gVar4, aVar7, 0);
        o.h(dVar3, "mlAudioController");
        o.h(cVar37, "tracker");
        o.h(dVar4, "timeSource");
        o.h(bVar19, "scope");
        l lVar = new l(dVar3, bVar18, cVar37, dVar4, jVar2, bVar19, hVar, 1);
        a81.d dVar6 = this.u0;
        c cVar42 = this.u;
        c cVar43 = this.k;
        c cVar44 = this.r;
        b bVar20 = this.x;
        c cVar45 = this.q;
        au0.g gVar5 = this.h0;
        c cVar46 = this.X;
        c cVar47 = this.c0;
        c cVar48 = this.z;
        o.h(dVar6, "processor");
        o.h(cVar42, "apiServiceFactory");
        o.h(cVar43, "storage");
        o.h(cVar44, "tracker");
        o.h(bVar20, "scope");
        o.h(cVar45, "sampleRate");
        o.h(gVar5, "codecs");
        o.h(cVar46, "mixEditorStorageController");
        o.h(cVar47, "clock");
        o.h(cVar48, "remoteConfig");
        a81.d dVar7 = new a81.d(new com.bandlab.audio.controller.voiceCleaner.a(dVar6, cVar42, cVar43, cVar44, bVar20, cVar45, gVar5, cVar46, cVar47, cVar48, 0), 13);
        c cVar49 = this.k;
        o.h(cVar49, "storage");
        a51.b bVar21 = new a51.b(cVar49, 17);
        c cVar50 = this.u;
        c cVar51 = this.k;
        o.h(cVar51, "storage");
        a51.b bVar22 = new a51.b(cVar51, 17);
        d dVar8 = this.o0;
        o.h(cVar50, "apiServiceFactory");
        o.h(dVar8, "remoteTaskProcessor");
        ah1.h hVar2 = new ah1.h(cVar50, bVar22, dVar8, 5);
        c cVar52 = this.k;
        o.h(cVar52, "storage");
        a51.b bVar23 = new a51.b(cVar52, 17);
        c cVar53 = this.q;
        o.h(cVar53, "sampleRate");
        ao0.g gVar6 = new ao0.g(8, bVar23, cVar53);
        jw1.c cVar54 = this.g;
        c cVar55 = this.k;
        o.h(cVar55, "storage");
        ao0.g gVar7 = new ao0.g(7, cVar54, new a51.b(cVar55, 17));
        b bVar24 = this.x;
        i iVar2 = this.R;
        df0.a aVar8 = this.Q;
        g gVar8 = this.s;
        c cVar56 = this.r;
        d dVar9 = this.k0;
        d dVar10 = this.P;
        o.h(bVar24, "scope");
        o.h(iVar2, "trackColorsProvider");
        o.h(aVar8, "trackNameProvider");
        o.h(gVar8, "res");
        o.h(cVar56, "tracker");
        o.h(dVar9, "timeSource");
        o.h(dVar10, "studioMaxTracksProvider");
        am.b bVar25 = new am.b(bVar21, hVar2, gVar6, gVar7, bVar24, iVar2, aVar8, gVar8, cVar56, dVar9, dVar10);
        jw1.c cVar57 = this.c;
        jw1.c cVar58 = this.b;
        jw1.c cVar59 = this.d;
        c cVar60 = this.u;
        d dVar11 = this.k0;
        c cVar61 = this.r;
        jw1.c cVar62 = this.g;
        au0.g gVar9 = this.r0;
        c cVar63 = this.m;
        c cVar64 = this.q;
        df0.a aVar9 = this.l;
        c cVar65 = this.N;
        o.h(gVar9, "mixDownRenderer");
        o.h(cVar63, "fxManagerProvider");
        o.h(cVar64, "sampleRate");
        o.h(aVar9, "workDirs");
        o.h(cVar65, "mixAdapter");
        g0 g0Var = new g0(gVar9, cVar63, cVar64, aVar9, cVar65, 1);
        d dVar12 = this.o0;
        c cVar66 = this.k;
        o.h(cVar60, "apiServiceFactory");
        o.h(dVar11, "timeSource");
        o.h(cVar61, "tracker");
        o.h(dVar12, "remoteTaskProcessor");
        o.h(cVar66, "storage");
        l lVar2 = new l(cVar60, dVar11, cVar61, cVar62, g0Var, dVar12, cVar66);
        c cVar67 = this.t;
        c cVar68 = this.X;
        c cVar69 = this.k;
        b bVar26 = this.x;
        jw1.c cVar70 = this.g;
        i iVar3 = this.R;
        g gVar10 = this.s;
        d dVar13 = this.l0;
        c cVar71 = this.p;
        d dVar14 = this.P;
        d dVar15 = this.T;
        o.h(cVar67, "importController");
        o.h(cVar68, "mixEditorStorageController");
        o.h(cVar69, "mixEditorStorage");
        o.h(bVar26, "scope");
        o.h(iVar3, "trackColors");
        o.h(gVar10, "resourcesProvider");
        o.h(dVar13, "tracker");
        o.h(cVar71, "ticksPerQuarter");
        o.h(dVar14, "studioMaxTracksProvider");
        o.h(dVar15, "autoPitchProvider");
        am.b bVar27 = new am.b(cVar67, cVar68, cVar69, bVar26, cVar70, iVar3, gVar10, dVar13, cVar71, dVar14, dVar15);
        jw1.c cVar72 = this.g;
        df0.a aVar10 = this.l;
        df0.a aVar11 = this.n;
        c cVar73 = this.q;
        o.h(aVar10, "workDirs");
        o.h(aVar11, "fxManager");
        o.h(cVar73, "sampleRate");
        b81.c cVar74 = new b81.c(cVar72, aVar10, aVar11, cVar73, 5);
        c cVar75 = this.k;
        o.h(cVar75, "storage");
        df0.a aVar12 = new df0.a(cVar75, 4);
        d dVar16 = this.j0;
        c cVar76 = this.X;
        b bVar28 = this.x;
        d dVar17 = this.k0;
        c cVar77 = this.r;
        o.h(dVar16, "mlAudioController");
        o.h(cVar76, "mixEditorStorageController");
        o.h(bVar28, "scope");
        o.h(dVar17, "timeSource");
        o.h(cVar77, "tracker");
        l lVar3 = new l(cVar74, aVar12, dVar16, cVar76, bVar28, dVar17, cVar77, 4);
        b bVar29 = this.i;
        b bVar30 = this.d0;
        b bVar31 = this.o;
        c cVar78 = this.k;
        c cVar79 = this.h;
        d dVar18 = this.p0;
        c cVar80 = this.p;
        c cVar81 = this.W;
        c cVar82 = this.Y;
        b bVar32 = this.x;
        d dVar19 = this.t0;
        o.h(bVar32, "scope");
        o.h(dVar19, "appLevelFactory");
        jq0.d dVar20 = new jq0.d(bVar32, dVar19, 1);
        d dVar21 = this.s0;
        b bVar33 = this.x;
        c cVar83 = this.r;
        c cVar84 = this.q;
        d dVar22 = this.g0;
        d dVar23 = this.q0;
        o.h(bVar15, "io");
        o.h(bVar29, "outDevice");
        o.h(bVar30, "inDevice");
        o.h(bVar31, "mixHandler");
        o.h(cVar78, "mixEditorStorage");
        o.h(dVar18, "latencyRepository");
        o.h(cVar80, "ticksPerQuarter");
        o.h(cVar81, "resourceManager");
        o.h(cVar82, "revisionChecker");
        o.h(dVar21, "studioSaver");
        o.h(bVar33, "scope");
        o.h(cVar83, "tracker");
        o.h(cVar84, "sampleRate");
        o.h(dVar22, "jsonMapper");
        o.h(dVar23, "pendingStudioState");
        this.v0 = new jw1.d(new zj.a(cVar32, bVar15, aVar6, lVar, dVar7, bVar25, cVar57, cVar58, cVar59, lVar2, bVar27, lVar3, bVar29, bVar30, bVar31, cVar78, cVar79, dVar18, cVar80, cVar81, cVar82, dVar20, dVar21, bVar33, cVar83, cVar84, dVar22, dVar23));
        jw1.c cVar85 = this.b;
        vl.a aVarZ = t0.z(this.g, this.l, this.f184j, this.R, this.Q, this.s, this.n);
        c cVar86 = this.k;
        o.h(cVar86, "storage");
        v31.a aVar13 = new v31.a(cVar86, 8);
        c cVar87 = this.u;
        o.h(cVar87, "apiServiceFactory");
        vl.e eVar = new vl.e(aVar13, cVar87, 0);
        c cVar88 = this.k;
        o.h(cVar88, "storage");
        v31.a aVar14 = new v31.a(cVar88, 8);
        b bVar34 = this.f184j;
        o.h(bVar34, "transport");
        v31.a aVar15 = new v31.a(bVar34, 9);
        b bVar35 = this.n0;
        b bVar36 = this.x;
        c cVar89 = this.r;
        d dVar24 = this.k0;
        d dVar25 = this.P;
        b bVar37 = this.v0;
        jw1.f fVar8 = this.a0;
        c cVar90 = this.u;
        o.h(bVar35, "midiRecomposePlayer");
        o.h(bVar36, "scope");
        o.h(cVar89, "tracker");
        o.h(dVar24, "timeSource");
        o.h(dVar25, "studioMaxTracksProvider");
        o.h(bVar37, "subControllerMixerConnector");
        o.h(fVar8, "smartComposeSessionHandlerFactory");
        o.h(cVar90, "apiServiceFactory");
        jw1.b.g(cVar85, new fg0.b(aVarZ, eVar, aVar14, aVar15, bVar35, bVar36, cVar89, dVar24, dVar25, bVar37, fVar8, cVar90));
        jw1.c cVar91 = this.c;
        vl.a aVarZ2 = t0.z(this.g, this.l, this.f184j, this.R, this.Q, this.s, this.n);
        c cVar92 = this.k;
        o.h(cVar92, "storage");
        v31.a aVar16 = new v31.a(cVar92, 8);
        c cVar93 = this.u;
        o.h(cVar93, "apiServiceFactory");
        vl.e eVar2 = new vl.e(aVar16, cVar93, 0);
        c cVar94 = this.k;
        o.h(cVar94, "storage");
        v31.a aVar17 = new v31.a(cVar94, 8);
        b bVar38 = this.f184j;
        o.h(bVar38, "transport");
        v31.a aVar18 = new v31.a(bVar38, 9);
        b bVar39 = this.e0;
        b bVar40 = this.x;
        b bVar41 = this.f184j;
        o.h(bVar41, "transport");
        v31.a aVar19 = new v31.a(bVar41, 9);
        a aVar20 = this.m0;
        o.h(bVar39, "io");
        o.h(bVar40, "scope");
        o.h(aVar20, "timerUpdateFrequencyMs");
        wl.f fVar9 = new wl.f(bVar39, bVar40, aVar19, aVar20, 0);
        b bVar42 = this.x;
        c cVar95 = this.r;
        d dVar26 = this.k0;
        b bVar43 = this.v0;
        jw1.f fVar10 = this.a0;
        c cVar96 = this.u;
        o.h(bVar42, "scope");
        o.h(cVar95, "tracker");
        o.h(dVar26, "timeSource");
        o.h(bVar43, "subControllerMixerConnector");
        o.h(fVar10, "smartComposeSessionHandlerFactory");
        o.h(cVar96, "apiServiceFactory");
        jw1.b.g(cVar91, new am.b(aVarZ2, eVar2, aVar17, aVar18, fVar9, bVar42, cVar95, dVar26, bVar43, fVar10, cVar96));
        jw1.c cVar97 = this.d;
        b bVar44 = this.e0;
        df0.a aVar21 = this.l;
        b bVar45 = this.f184j;
        df0.a aVar22 = this.n;
        b bVar46 = this.x;
        c cVar98 = this.k;
        c cVar99 = this.N;
        d dVar27 = this.P;
        d dVar28 = this.f0;
        a aVar23 = new a(this, 0);
        c cVar100 = this.z;
        g gVar11 = this.s;
        d dVar29 = this.g0;
        b bVar47 = this.v0;
        c cVar101 = this.W;
        jw1.f fVar11 = this.a0;
        c cVar102 = this.u;
        o.h(bVar44, "io");
        o.h(aVar21, "workDirs");
        o.h(bVar45, "transport");
        o.h(aVar22, "fxManager");
        o.h(bVar46, "scope");
        o.h(cVar98, "storage");
        o.h(cVar99, "mixAdapter");
        o.h(dVar27, "studioMaxTracksProvider");
        o.h(dVar28, "audioFilesValidator");
        o.h(cVar100, "remoteConfig");
        o.h(gVar11, "resourcesProvider");
        o.h(dVar29, "jsonMapper");
        o.h(bVar47, "subControllerMixerConnector");
        o.h(cVar101, "meResManager");
        o.h(fVar11, "smartComposeSessionHandlerFactory");
        o.h(cVar102, "apiServiceFactory");
        jw1.b.g(cVar97, new i80.f(bVar44, aVar21, bVar45, aVar22, bVar46, cVar98, cVar99, dVar27, dVar28, aVar23, cVar100, gVar11, dVar29, bVar47, cVar101, fVar11, cVar102));
        jw1.c cVar103 = this.e;
        b bVar48 = this.x;
        a81.d dVar30 = this.u0;
        c cVar104 = this.z;
        c cVar105 = this.y;
        o.h(bVar48, "scope");
        o.h(dVar30, "mixProcessor");
        o.h(cVar104, "remoteConfig");
        o.h(cVar105, "availabilityProvider");
        jw1.b.g(cVar103, new ct.b(bVar48, (b) dVar30, (b) cVar104, (b) cVar105, 6));
        jw1.c cVar106 = this.f183f;
        b bVar49 = this.x;
        a81.d dVar31 = this.u0;
        c cVar107 = this.w;
        o.h(bVar49, "scope");
        o.h(dVar31, "mixProcessor");
        o.h(cVar107, "availabilityProvider");
        jw1.b.g(cVar106, new f0(bVar49, (b) dVar31, (b) cVar107, 8));
        jw1.c cVar108 = this.g;
        b bVar50 = this.o;
        b bVar51 = this.f184j;
        c cVar109 = this.K;
        c cVar110 = this.k;
        c cVar111 = this.O;
        b bVar52 = this.x;
        df0.a aVar24 = this.l;
        c cVar112 = this.t;
        c cVar113 = this.z;
        b bVar53 = this.v;
        d dVar32 = this.T;
        au0.g gVar12 = this.L;
        c cVar114 = this.N;
        c cVar115 = this.W;
        i iVar4 = this.R;
        df0.a aVar25 = this.Q;
        g gVar13 = this.s;
        c cVar116 = this.M;
        d dVar33 = this.P;
        jw1.c cVar117 = this.e;
        c cVar118 = this.X;
        c cVar119 = this.r;
        c cVar120 = this.C;
        c cVar121 = this.A;
        c cVar122 = this.I;
        jw1.f fVar12 = this.J;
        jw1.c cVar123 = this.f183f;
        au0.g gVar14 = this.U;
        d dVar34 = this.S;
        au0.g gVar15 = this.V;
        a aVar26 = new a(this, 1);
        b bVar54 = this.v0;
        o.h(bVar54, "audioControllerCore");
        df0.a aVar27 = new df0.a(this, bVar54, 29);
        b bVar55 = this.v0;
        o.h(bVar55, "audioControllerCore");
        df0.a aVar28 = new df0.a(this, bVar55, 28);
        o.h(bVar50, "mixer");
        o.h(bVar51, "transport");
        o.h(cVar109, "audioFocus");
        o.h(cVar110, "mixEditorStorage");
        o.h(cVar111, "preferences");
        o.h(bVar52, "scope");
        o.h(aVar24, "workDirs");
        o.h(cVar112, "importer");
        o.h(cVar113, "remoteConfig");
        o.h(bVar53, "presetCache");
        o.h(dVar32, "autoPitchProvider");
        o.h(gVar12, "pitchShiftCalculator");
        o.h(cVar114, "mixAdapter");
        o.h(cVar115, "studioResources");
        o.h(iVar4, "trackColorsProvider");
        o.h(aVar25, "defaultTrackNameProvider");
        o.h(gVar13, "resourcesProvider");
        o.h(cVar116, "userIdProvider");
        o.h(dVar33, "studioMaxTracksProvider");
        o.h(cVar118, "mixEditorStorageController");
        o.h(cVar119, "tracker");
        o.h(cVar120, "membershipRepo");
        o.h(cVar121, "membersEffectsRepo");
        o.h(cVar122, "effectDataParser");
        o.h(fVar12, "presetControllerFactory");
        o.h(gVar14, "premiumFeaturesAvailabilityProvider");
        o.h(dVar34, "premiumFeaturesPermissionProvider");
        o.h(gVar15, "studioCompingAvailabilityProvider");
        jw1.b.g(cVar108, new jw1.d(new p90.d(bVar50, bVar51, cVar109, cVar110, cVar111, bVar52, aVar24, cVar112, cVar113, bVar53, dVar32, gVar12, cVar114, cVar115, iVar4, aVar25, gVar13, cVar116, dVar33, cVar117, cVar118, cVar119, cVar120, cVar121, cVar122, fVar12, cVar123, gVar14, dVar34, gVar15, aVar26, aVar27, aVar28)));
    }
}
